title: "Hemalatha Sekar Portfolio"
email: "hematechie@gmail.com"
description: "A portfolio showcasing my work and skills in Data Science and Software Development."
baseurl: "/hemababy.github.io"
url: "https://hemababy.github.io"
